/*
 *  f1livetiming - Part of the Live Timing Library for .NET
 *  Copyright (C) 2009 Liam Lowey
 *  
 *      http://livetiming.turnitin.co.uk/
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); 
 *  you may not use this file except in compliance with the License. 
 *  You may obtain a copy of the License at 
 *  
 *      http://www.apache.org/licenses/LICENSE-2.0 
 *  
 *  Unless required by applicable law or agreed to in writing, software 
 *  distributed under the License is distributed on an "AS IS" BASIS, 
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *  See the License for the specific language governing permissions and 
 *  limitations under the License. 
 */

using System.IO;
using F1.Data.Packets;
using F1.Enums;

namespace F1.Messages
{
    /// <summary>
    /// This defines the basic interface of every message generated by implementations of <see cref="ILiveTimingApp"/>.
    /// </summary>
    public interface IMessage
    {
        /// <summary>
        /// Internal method, do not use.
        /// </summary>
        Packet CreatePacketType(Header header, Stream rawStream, Stream decryptStream);

        /// <summary>
        /// Internal method, do not use.
        /// </summary>
        void Deserialise(Header header, Packet payload);

        /// <summary>
        /// Defines the type of message represented in this implementation.
        /// </summary>
        SystemPacketType Type { get;  } 
    }
}
